### ISSUE TITLE
Socket fail to connect to mariadb:3333. Connection refused

### ISSUE THREAD

**Issue by jonebarker** [adityachandelgit/BookLore#338]
The database logs seem fine, but the booklore container shuts down after retries timeout.
```
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:118) ~[mariadb-java-client-3.5.3.jar!/:na]
	... 132 common frames omitted
```
Here is my yaml file which uses bind mounts and port mapping to avoid conflict with host port usage and other mariadb instances.  I've tried using .env variables too based on others' experience, but it didn't work.
```
#name: booklore
services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    container_name: booklore-server
    environment:
      - PUID=1006
      - PGID=100
      - TZ=America/New_York
      - DATABASE_URL=jdbc:mariadb://mariadb:3333/booklore # Only modify this if you're familiar with JDBC and your database setup
      - DATABASE_USERNAME=booklore # Must match MYSQL_USER defined in the mariadb container
      - DATABASE_PASSWORD=nope
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6061:6060"
      - "8065:80"
      - "8866:8080"
    
    volumes:
      - ${PATH_TO_APPDATA}/booklore/app/data:/app/data
      - ${PATH_TO_KB}:/books:ro
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore-mariadb
    environment:
      - PUID=1006
      - PGID=100
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=noper
      - MYSQL_DATABASE=booklore
      - MYSQL_USER=booklore # Must match DATABASE_USERNAME defined in the booklore container
      - MYSQL_PASSWORD=nope
      - DATABASE_PASSWORD defined in the booklore container
    ports:
      - "3333:3306"
    volumes:
      - ${PATH_TO_APPDATA}/booklore/mariadb/config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
```
Does this build even allow for me to change database ports like this?

**Comment by arcoast** [comment]
You tried 3306?  

The containers above should be running in the same docker network, so you would use the internal port not the external.

Here's my config for an example, I don't even open the ports host side as there's no need (as I run booklore behind traefik)

```yaml
networks:
    booklore:
        external: false
        name: booklore

services:
    booklore:
        image: ghcr.io/adityachandelgit/booklore-app:latest
        container_name: booklore
        networks:
            - booklore
            - traefik
        # ports:
        #     - 6060:6060
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
            - DATABASE_URL=jdbc:mariadb://booklore-mariadb:3306/${BOOKLORE_MYSQL_DATABASE}
            - DATABASE_USERNAME=${BOOKLORE_MYSQL_USER}
            - DATABASE_PASSWORD=${BOOKLORE_MYSQL_PASSWORD}
        volumes:
            - ${CONFIG}/booklore/booklore:/app/data
            - ${BOOKS}:/books
        restart: unless-stopped
        depends_on:
            booklore-mariadb:
                condition: service_healthy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.services.booklore.loadbalancer.server.port=6060"
            - "traefik.http.routers.booklore.entrypoints=websecure"
            - "traefik.http.routers.booklore.rule=Host(`booklore.${DOMAIN}`)"
            - "traefik.http.routers.booklore.middlewares=authelia@file, securityHeaders@file"

    booklore-mariadb:
        image: lscr.io/linuxserver/mariadb
        container_name: booklore-mariadb
        networks:
            - booklore
        # ports:
        #     - 3306:3306
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}          
            - MYSQL_USER=${BOOKLORE_MYSQL_USER}
            - MYSQL_PASSWORD=${BOOKLORE_MYSQL_PASSWORD}
            - MYSQL_DATABASE=${BOOKLORE_MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${BOOKLORE_MYSQL_ROOT_PASSWORD}
        volumes:
            - ${CONFIG}/booklore/booklore-mariadb:/config
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
```

My `.env`

```
BOOKLORE_MYSQL_USER=booklore
BOOKLORE_MYSQL_PASSWORD=PASSWORD
BOOKLORE_MYSQL_DATABASE=booklore
BOOKLORE_MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
```

**Comment by jonebarker** [comment]
I managed to resolve the issue. Even though I made concerted efforts to keep the ports unique on the host IP, there have been some conflict that I couldn't pin point.  So I created a macvlan, assigned an unique IP and everything ran smoothly afterwards.  After creating the network, I added it to the compose like this:

```
networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

```
