### ISSUE TITLE
Env_var to specify mariadb hostname

### ISSUE THREAD

**Issue by fabiopbx** [adityachandelgit/BookLore#9]
For those of us who have more then one mariadb, would be nice to have a way to set a env_var with the hostname of the mariadb for booklore, as it appears its hard coded to `mariadb`

`tests_booklore.1.s4ezhjhuprd9@node02    | Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Socket fail to connect to mariadb. mariadb`

**Comment by adityachandelgit** [comment]
Good idea!
Added these to the YAML file:

```
container_name: booklore_server
container_name: booklore_mariadb
name: booklore
```
Now booklore's mariadb will not have conflict with other mariadb instances.

```
name: booklore
services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:${BOOKLORE_IMAGE_TAG}
    container_name: booklore_server
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6060:6060"
    volumes:
      - ${BOOKLORE_DATA_PATH}:/app/data
      - ${BOOKLORE_BOOKS_PATH}:/books

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore_mariadb
    env_file:
      - .env
    volumes:
      - ${MARIADB_CONFIG_PATH}:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
```

**Comment by adityachandelgit** [comment]
@fabiopbx Let me know if you were able to get the application up and log in. It seems like several people are having trouble with the login process.

**Comment by fabiopbx** [comment]
Thanks for quick reply,

as far as i recall docker don't use container_name for its hostname, even if it does use that in my case i can't use that, since I'm deploying using docker swarm.

As far as i can tell, the connection string to the database appears to be hardcoded to use the hostname 'mariadb' and that's what it tries, this works fine as long as the service name is called 'mariadb', ie the first key in the yml:

`  mariadb: # <---- this here is what docker uses internally as a hostname
    image: lscr.io/linuxserver/mariadb:11.4.5`

so in my cases both containers are up, but the app is trying to connect to a hostname 'mariadb' that does not exists, since in my case i named it differently, that's why the env var is needed :)

` booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=nope
    networks:
      - net
    ports:
      - "6660:6060"
    volumes:
      - /home/user/docker/volumes/booklore_data:/app/data
      - booksLibrary:/books:ro
    deploy:
      placement:
        constraints:
          - node.hostname == node02

  booklore_db:
    image: lscr.io/linuxserver/mariadb:11.4.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=nope
    networks:
      - net
    volumes:
      - /home/user/docker/volumes/booklore_db_conf:/config
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.hostname == node02`

in another note i also noted the app container fails to start if it can't read/write to the library path

`      - booksLibrary:/books:ro
`

in my case without even throwing an error :( managed to get it to at least start by allowing write to it, maybe something to check ;)

**Comment by adityachandelgit** [comment]
Got it!

You’re right, the mariadb hostname is currently hardcoded in the datasource.url within the application.yml file. I’ll update it to be configurable through an environment variable for better flexibility.

```
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/booklore?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
```
I will push a update soon.
